version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./schemas:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'accesa_app'
      MYSQL_USER: 'edgar'
      MYSQL_PASSWORD: '1234'
    ports:
      - 3306:3306
volumes:
  schemas: {}
