version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    volumes:
      - ./schemas:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
volumes:
  schemas: {}
